Exercice 8 + Exercice 1 filejs_
HamzaJamalDev/js-exercices pull request #2
Opened 2022-11-25 11:14 UTC by clownvar

BERCHIL Idriss Grp 11

2022-11-25 11:36 UTC, HamzaJamalDev requested changes

2022-11-25 11:36 UTC, HamzaJamalDev commented on filejs_Tableaux.js
> +function PlusGrand(Tableau, nombre)
```suggestion
function PlusGrand(tableau, nombre)
```

2022-11-25 11:36 UTC, HamzaJamalDev commented on filejs_Tableaux.js
> +            console.log(i)
Retourner un tableau et l'afficher en dehors de la fonction

2022-11-25 11:36 UTC, HamzaJamalDev commented on filejs_Tableaux.js
> +}
Appelez la fonction et passez les arguments

2022-11-25 11:36 UTC, HamzaJamalDev commented on filejs_conditions_loops.js
> +//Exercice 8
C'est l'exercice 5 des fonctions! donc changez le fichier, créez une fonction et l'appeler

2022-11-30 07:20 UTC, HamzaJamalDev commented
Regrouper les commits créés en un seul commit (utiliser _git rebase -i_ ou autre méthode)

2022-12-09 19:33 UTC, clownvar commented
Les branch a était rebased, priére de merger.

2022-12-13 09:02 UTC, merged