Solution des exercices
HamzaJamalDev/js-exercices pull request #28
Opened 2022-12-05 21:12 UTC by ibtissamdaraaoui

Daraaoui Ibtissam 3IIR groupe3

2022-12-13 18:42 UTC, HamzaJamalDev requested changes

2022-12-13 18:42 UTC, HamzaJamalDev commented on Solutions des exercices
> +               t=count;
Vous changez la valeur du tableau à chaque fois, il prendra juste la valeur finale du **nombre**.

2022-12-13 18:42 UTC, HamzaJamalDev commented on Solutions des exercices
> +               for(let k=0;k<t.length;k++){
Par conséquent, _t_ n'a pas la propriété _length_.

2022-12-13 18:42 UTC, HamzaJamalDev commented on Solutions des exercices
> +            }
L'imbrication des boucles est mal définie.

2022-12-15 20:20 UTC, ibtissamdaraaoui commented
Monsieur j'ai supprimé les solutions déjà existantes et corriger les autres

2022-12-15 20:57 UTC, closed without merging