update
HamzaJamalDev/js-exercices pull request #9
Opened 2022-11-26 02:41 UTC by rimwakil

//exercice 6 sur les fonctions recursive

let n  = prompt("donner un nombre");
function factorielle(n) {
    // 0! =1, 1! =1   
    if(n===0||n===1){
  return 1;
   }
   else{ 
    return n * factorielle(n-1)
   }
       
}
 console.log(factorielle(n));

 //exercice 1 sur les tableaux
 function greaterThan(tab,n){
    let t =[] ;
    for(let i=0; i<tab.length ;i++){
        if(tab[i]>n){
            t.push(tab[i]);
        }
    }
    return t
 }
 let t=[6,8,-2,4];
 let n=-1;
 console.log(greaterThan(t,n));

2022-11-26 17:39 UTC, rimwakil commented
rim wakil grp1

2022-11-30 18:31 UTC, HamzaJamalDev requested changes

2022-11-30 18:31 UTC, HamzaJamalDev commented on README.md
> +# js-exercices
Ajoutez ces modifications dans un fichier JavaScript

2022-12-02 18:42 UTC, closed without merging

2022-12-02 22:58 UTC, rimwakil reviewed
files changed